In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("laptop_data.csv")
df.head(20)
df.shape
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [3]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [4]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [7]:
df['Company'].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [8]:
df['TypeName'].unique()

array(['Ultrabook', 'Notebook', 'Netbook', 'Gaming', '2 in 1 Convertible',
       'Workstation'], dtype=object)

In [9]:
df['Inches'].dtype

dtype('float64')

In [10]:
df['Inches'].describe()

count    1303.000000
mean       15.017191
std         1.426304
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.400000
Name: Inches, dtype: float64

In [11]:
df['Inches'] = df['Inches'].astype(int)
df['Inches']

0       13
1       13
2       15
3       15
4       13
        ..
1298    14
1299    13
1300    14
1301    15
1302    15
Name: Inches, Length: 1303, dtype: int64

In [12]:
df['ScreenResolution'].unique()

array(['IPS Panel Retina Display 2560x1600', '1440x900',
       'Full HD 1920x1080', 'IPS Panel Retina Display 2880x1800',
       '1366x768', 'IPS Panel Full HD 1920x1080',
       'IPS Panel Retina Display 2304x1440',
       'IPS Panel Full HD / Touchscreen 1920x1080',
       'Full HD / Touchscreen 1920x1080',
       'Touchscreen / Quad HD+ 3200x1800',
       'IPS Panel Touchscreen 1920x1200', 'Touchscreen 2256x1504',
       'Quad HD+ / Touchscreen 3200x1800', 'IPS Panel 1366x768',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'IPS Panel Full HD 2160x1440',
       '4K Ultra HD / Touchscreen 3840x2160', 'Touchscreen 2560x1440',
       '1600x900', 'IPS Panel 4K Ultra HD 3840x2160',
       '4K Ultra HD 3840x2160', 'Touchscreen 1366x768',
       'IPS Panel Full HD 1366x768', 'IPS Panel 2560x1440',
       'IPS Panel Full HD 2560x1440',
       'IPS Panel Retina Display 2736x1824', 'Touchscreen 2400x1600',
       '2560x1440', 'IPS Panel Quad HD+ 2560x1440',
       'IPS Panel Quad HD+ 3200x1800',
       'IPS Panel Quad HD+ / Touchscreen 3200x1800',
       'IPS Panel Touchscreen 1366x768', '1920x1080',
       'IPS Panel Full HD 1920x1200',
       'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2560x1440',
       'Touchscreen / Full HD 1920x1080', 'Quad HD+ 3200x1800',
       'Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2400x1600'], dtype=object)

In [13]:
df['ScreenResolution'] = df['ScreenResolution'].str.strip()

In [14]:
df['Resolution_Width'] = df['ScreenResolution'].str.split('x').str[0]
df['Resolution_Width'] = df['Resolution_Width'].str.split().str[-1]

In [15]:
df['Resolution_Height'] = df['ScreenResolution'].str.split('x').str[1]

In [16]:
print(df['Resolution_Height'])

0       1600
1        900
2       1080
3       1800
4       1600
        ...
1298    1080
1299    1800
1300     768
1301     768
1302     768
Name: Resolution_Height, Length: 1303, dtype: object

In [17]:
df[['ScreenResolution', 'Resolution_Width', 'Resolution_Height']].head()

                     ScreenResolution Resolution_Width Resolution_Height
0  IPS Panel Retina Display 2560x1600             2560              1600
1                            1440x900             1440               900
2                   Full HD 1920x1080             1920              1080
3  IPS Panel Retina Display 2880x1800             2880              1800
4  IPS Panel Retina Display 2560x1600             2560              1600

In [18]:
df['Touchscreen'] = np.where(df['ScreenResolution'].str.contains('Touchscreen'),1,0)

In [19]:
df['Touchscreen'].value_counts()

Touchscreen
0    1111
1     192
Name: count, dtype: int64

In [20]:
df['IPS'] = np.where(df['ScreenResolution'].str.contains('IPS'),1,0)

In [21]:
df['IPS'].value_counts()

IPS
0    938
1    365
Name: count, dtype: int64

In [22]:
df['Cpu'].dtype

dtype('O')

In [23]:
df['Cpu'].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'AMD A10-Series 9620P 2.5GHz',
       'AMD E-Series 7110 1.8GHz', 'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)

In [24]:
df['Cpu_GHz'] = df['Cpu'].str.extract(r'(\d+\.?\d*)GHz')[0]

In [25]:
df['Cpu_GHz'] = df['Cpu_GHz'].astype(float)

In [26]:
df[['Cpu', 'Cpu_GHz']].head()

                          Cpu  Cpu_GHz
0        Intel Core i5 2.3GHz      2.3
1        Intel Core i5 1.8GHz      1.8
2  Intel Core i5 7200U 2.5GHz      2.5
3        Intel Core i7 2.7GHz      2.7
4        Intel Core i5 3.1GHz      3.1

In [27]:
df['Cpu_GHz'].isnull().sum()

np.int64(0)

In [28]:
df['Cpu_Brand'] = df['Cpu'].str.split().str[0]

In [29]:
df['Cpu_Brand'].value_counts()

Cpu_Brand
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64

In [30]:
df['Cpu'].head(10)

0          Intel Core i5 2.3GHz
1          Intel Core i5 1.8GHz
2    Intel Core i5 7200U 2.5GHz
3          Intel Core i7 2.7GHz
4          Intel Core i5 3.1GHz
5       AMD A9-Series 9420 3GHz
6          Intel Core i7 2.2GHz
7          Intel Core i5 1.8GHz
8    Intel Core i7 8550U 1.8GHz
9    Intel Core i5 8250U 1.6GHz
Name: Cpu, dtype: object

In [31]:
df['Cpu_Type'] = df['Cpu'].str.extract(r'(Core i[357]|Ryzen|Celeron|Pentium|Atom|Xeon|Core M)')

In [32]:
df['Cpu_Type'].value_counts()

Cpu_Type
Core i7    527
Core i5    423
Core i3    136
Celeron     88
Pentium     30
Core M      19
Atom        13
Ryzen        4
Xeon         4
Name: count, dtype: int64

In [33]:
df[['Cpu', 'Cpu_Brand', 'Cpu_Type', 'Cpu_GHz']].head(10)

                          Cpu Cpu_Brand Cpu_Type  Cpu_GHz
0        Intel Core i5 2.3GHz     Intel  Core i5      2.3
1        Intel Core i5 1.8GHz     Intel  Core i5      1.8
2  Intel Core i5 7200U 2.5GHz     Intel  Core i5      2.5
3        Intel Core i7 2.7GHz     Intel  Core i7      2.7
4        Intel Core i5 3.1GHz     Intel  Core i5      3.1
5     AMD A9-Series 9420 3GHz       AMD      NaN      3.0
6        Intel Core i7 2.2GHz     Intel  Core i7      2.2
7        Intel Core i5 1.8GHz     Intel  Core i5      1.8
8  Intel Core i7 8550U 1.8GHz     Intel  Core i7      1.8
9  Intel Core i5 8250U 1.6GHz     Intel  Core i5      1.6

In [34]:
df['Ram'].dtype

dtype('O')

In [35]:
df['Ram'].unique()

array(['8GB', '16GB', '4GB', '2GB', '12GB', '6GB', '32GB', '24GB', '64GB'],
      dtype=object)

In [36]:
df['Ram'] = df['Ram'].str.replace('GB', '')

In [37]:
df['Ram'] = df['Ram'].astype(int)

In [38]:
df['Ram'].dtype

dtype('int64')

In [39]:
df['Ram'].unique()

array([ 8, 16,  4,  2, 12,  6, 32, 24, 64])

In [40]:
df['Memory'].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '32GB Flash Storage', '128GB SSD +  1TB HDD',
       '256GB SSD +  256GB SSD', '64GB Flash Storage',
       '256GB SSD +  1TB HDD', '256GB SSD +  2TB HDD', '32GB SSD',
       '2TB HDD', '64GB SSD', '1.0TB Hybrid', '512GB SSD +  1TB HDD',
       '1TB SSD', '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [41]:
df['SSD'] = df['Memory'].str.extract(r'(\d+(?:\.\d+)?)GB SSD')[0]
df["SSD"]

0       128
1       NaN
2       256
3       512
4       256
       ...
1298    128
1299    512
1300    NaN
1301    NaN
1302    NaN
Name: SSD, Length: 1303, dtype: object

In [42]:
df['Memory'].isnull().sum()

np.int64(0)

In [43]:
df[['Memory', 'SSD']].head(10)

                Memory  SSD
0            128GB SSD  128
1  128GB Flash Storage  NaN
2            256GB SSD  256
3            512GB SSD  512
4            256GB SSD  256
5            500GB HDD  NaN
6  256GB Flash Storage  NaN
7  256GB Flash Storage  NaN
8            512GB SSD  512
9            256GB SSD  256

In [44]:
df['HDD'] = df['Memory'].str.extract(r'(\d+)GB HDD')

In [45]:
df[['Memory', 'HDD']].head(10)

                Memory  HDD
0            128GB SSD  NaN
1  128GB Flash Storage  NaN
2            256GB SSD  NaN
3            512GB SSD  NaN
4            256GB SSD  NaN
5            500GB HDD  500
6  256GB Flash Storage  NaN
7  256GB Flash Storage  NaN
8            512GB SSD  NaN
9            256GB SSD  NaN

In [46]:
df.loc[df['Memory'].str.contains('TB HDD'), 'HDD'] = (
    df.loc[df['Memory'].str.contains('TB HDD'), 'Memory']
    .str.extract(r'(\d+(?:\.\d+)?)TB HDD')[0]
    .astype(float) * 1024)

In [47]:
df['HDD'] = df['HDD'].astype(float)

In [48]:
df[['Memory', 'HDD']].head(20)

                 Memory     HDD
0             128GB SSD     NaN
1   128GB Flash Storage     NaN
2             256GB SSD     NaN
3             512GB SSD     NaN
4             256GB SSD     NaN
5             500GB HDD   500.0
6   256GB Flash Storage     NaN
7   256GB Flash Storage     NaN
8             512GB SSD     NaN
9             256GB SSD     NaN
10            500GB HDD   500.0
11            500GB HDD   500.0
12            256GB SSD     NaN
13            256GB SSD     NaN
14            256GB SSD     NaN
15            256GB SSD     NaN
16            256GB SSD     NaN
17            512GB SSD     NaN
18              1TB HDD  1024.0
19            128GB SSD     NaN

In [49]:
df['HDD'] = df['HDD'].astype('Int64')

In [50]:
df[['Memory', 'SSD', 'HDD']].head(20)

                 Memory  SSD   HDD
0             128GB SSD  128  <NA>
1   128GB Flash Storage  NaN  <NA>
2             256GB SSD  256  <NA>
3             512GB SSD  512  <NA>
4             256GB SSD  256  <NA>
5             500GB HDD  NaN   500
6   256GB Flash Storage  NaN  <NA>
7   256GB Flash Storage  NaN  <NA>
8             512GB SSD  512  <NA>
9             256GB SSD  256  <NA>
10            500GB HDD  NaN   500
11            500GB HDD  NaN   500
12            256GB SSD  256  <NA>
13            256GB SSD  256  <NA>
14            256GB SSD  256  <NA>
15            256GB SSD  256  <NA>
16            256GB SSD  256  <NA>
17            512GB SSD  512  <NA>
18              1TB HDD  NaN  1024
19            128GB SSD  128  <NA>

In [51]:
df['Flash_Storage'] = df['Memory'].str.extract(r'(\d+(?:\.\d+)?)GB Flash Storage')

In [52]:
df[['Memory', 'Flash_Storage']].head(20)

                 Memory Flash_Storage
0             128GB SSD           NaN
1   128GB Flash Storage           128
2             256GB SSD           NaN
3             512GB SSD           NaN
4             256GB SSD           NaN
5             500GB HDD           NaN
6   256GB Flash Storage           256
7   256GB Flash Storage           256
8             512GB SSD           NaN
9             256GB SSD           NaN
10            500GB HDD           NaN
11            500GB HDD           NaN
12            256GB SSD           NaN
13            256GB SSD           NaN
14            256GB SSD           NaN
15            256GB SSD           NaN
16            256GB SSD           NaN
17            512GB SSD           NaN
18              1TB HDD           NaN
19            128GB SSD           NaN

In [53]:
df['Flash_Storage'] = df['Flash_Storage'].astype(float)

In [54]:
hybrid = df['Memory'].str.extract(r'(\d+(?:\.\d+)?)(GB|TB) Hybrid')

df['Hybrid'] = hybrid[0].astype(float)

df.loc[hybrid[1] == 'TB', 'Hybrid'] = (
    df.loc[hybrid[1] == 'TB', 'Hybrid'] * 1024
)

In [55]:
df[['Memory', 'Flash_Storage', 'Hybrid']].head(20)

                 Memory  Flash_Storage  Hybrid
0             128GB SSD            NaN     NaN
1   128GB Flash Storage          128.0     NaN
2             256GB SSD            NaN     NaN
3             512GB SSD            NaN     NaN
4             256GB SSD            NaN     NaN
5             500GB HDD            NaN     NaN
6   256GB Flash Storage          256.0     NaN
7   256GB Flash Storage          256.0     NaN
8             512GB SSD            NaN     NaN
9             256GB SSD            NaN     NaN
10            500GB HDD            NaN     NaN
11            500GB HDD            NaN     NaN
12            256GB SSD            NaN     NaN
13            256GB SSD            NaN     NaN
14            256GB SSD            NaN     NaN
15            256GB SSD            NaN     NaN
16            256GB SSD            NaN     NaN
17            512GB SSD            NaN     NaN
18              1TB HDD            NaN     NaN
19            128GB SSD            NaN     NaN

In [56]:
df['Gpu'] = df['Gpu'].str.strip()

In [57]:
df['Gpu_Brand'] = df['Gpu'].str.split().str[0]

In [58]:
df['Gpu_Brand'].value_counts()

Gpu_Brand
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [59]:
df['Gpu_Brand'] = df['Gpu_Brand'].str.capitalize()
df['Gpu_Brand']

0       Intel
1       Intel
2       Intel
3         Amd
4       Intel
        ...
1298    Intel
1299    Intel
1300    Intel
1301      Amd
1302    Intel
Name: Gpu_Brand, Length: 1303, dtype: object

In [60]:
df['Gpu_Model'] = df['Gpu'].str.replace(
    df['Gpu_Brand'] + ' ', '', regex=False
)

In [61]:
df[['Gpu', 'Gpu_Brand', 'Gpu_Model']].head(10)

                            Gpu Gpu_Brand  Gpu_Model
0  Intel Iris Plus Graphics 640     Intel        NaN
1        Intel HD Graphics 6000     Intel        NaN
2         Intel HD Graphics 620     Intel        NaN
3            AMD Radeon Pro 455       Amd        NaN
4  Intel Iris Plus Graphics 650     Intel        NaN
5                 AMD Radeon R5       Amd        NaN
6       Intel Iris Pro Graphics     Intel        NaN
7        Intel HD Graphics 6000     Intel        NaN
8          Nvidia GeForce MX150    Nvidia        NaN
9        Intel UHD Graphics 620     Intel        NaN

In [62]:
df['OpSys'].unique()

array(['macOS', 'No OS', 'Windows 10', 'Mac OS X', 'Linux', 'Android',
       'Windows 10 S', 'Chrome OS', 'Windows 7'], dtype=object)

In [63]:
df['OpSys'] = df['OpSys'].replace({
    'Mac OS X': 'macOS'})

In [64]:
df['OpSys'] = df['OpSys'].replace({
    'Windows 10 S': 'Windows',
    'Windows 10': 'Windows',
    'Windows 7': 'Windows'})

In [65]:
df['OpSys'].value_counts()

OpSys
Windows      1125
No OS          66
Linux          62
Chrome OS      27
macOS          21
Android         2
Name: count, dtype: int64

In [66]:
df['Weight'].dtype

dtype('O')

In [67]:
df['Weight'] = df['Weight'].str.replace('kg', '')

In [68]:
df['Weight'] = df['Weight'].astype(float)
df['Weight']

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: Weight, Length: 1303, dtype: float64

In [69]:
df['Weight'].dtype

dtype('float64')

In [70]:
df[['Ram', 'Weight']].head()

   Ram  Weight
0    8    1.37
1    8    1.34
2    8    1.86
3   16    1.83
4    8    1.37

In [71]:
df['HDD'] = df['HDD'].fillna(0).astype(float)

In [72]:
df.isnull().sum()

Company                 0
TypeName                0
Inches                  0
ScreenResolution        0
Cpu                     0
Ram                     0
Memory                  0
Gpu                     0
OpSys                   0
Weight                  0
Price                   0
Resolution_Width        0
Resolution_Height       0
Touchscreen             0
IPS                     0
Cpu_GHz                 0
Cpu_Brand               0
Cpu_Type               59
SSD                   476
HDD                     0
Flash_Storage        1228
Hybrid               1291
Gpu_Brand               0
Gpu_Model            1303
dtype: int64

In [73]:
df['Cpu_Type'] = df['Cpu_Type'].fillna('Unknown')
df['Gpu_Model'] = df['Gpu_Model'].fillna('Unknown')

df['SSD'] = df['SSD'].fillna(0)
df['Flash_Storage'] = df['Flash_Storage'].fillna(0)
df['Hybrid'] = df['Hybrid'].fillna(0)

In [74]:
df.isnull().sum()

Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys                0
Weight               0
Price                0
Resolution_Width     0
Resolution_Height    0
Touchscreen          0
IPS                  0
Cpu_GHz              0
Cpu_Brand            0
Cpu_Type             0
SSD                  0
HDD                  0
Flash_Storage        0
Hybrid               0
Gpu_Brand            0
Gpu_Model            0
dtype: int64

In [75]:
X = df.drop('Price', axis=1)
y = df['Price']

In [76]:
X = X.astype(str)

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_cols = X.select_dtypes(include='object').columns
numeric_cols = X.select_dtypes(exclude='object').columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', 'passthrough', numeric_cols)
    ]
)

X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [79]:
categorical_cols = X.select_dtypes(include='object').columns

X[categorical_cols] = X[categorical_cols].astype(str)

In [80]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [81]:
y_pred = dt.predict(X_test)

In [82]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2 Score: 0.5755002263550735
MSE: 612078026.0040957
MAE: 13829.869186206895

In [83]:
from sklearn.ensemble import RandomForestRegressor

In [84]:
rf = RandomForestRegressor(n_estimators=100,random_state=42)

In [85]:
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [86]:
y_pred_rf = rf.predict(X_test)

In [87]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MSE:", mean_squared_error(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

R2 Score: 0.7419816018745486
MSE: 372031745.603388
MAE: 10142.345300413794